### ISSUE TITLE
installation procedure should follow standard pip procedures

### ISSUE THREAD

**Issue by lucask07** [aid4mh/QPrism#1]
The installation step:

> pip install -r https://raw.githubusercontent.com/aid4mh/QPrism/main/requirements.txt

downgraded many of my Python packages including scipy and pandas and caused a few dependency conflicts. Are greater than or equal to (e.g. pandas>=1.2.4) versions in the requirements.txt possible?

**Comment by RahaviSelvarajan** [comment]
Please use the versions mentioned in the [requirements.txt](https://github.com/aid4mh/QPrism/blob/main/requirements.txt) file. 

Could you please let us know where you experienced dependency conflicts?

**Comment by lucask07** [comment]
The dependency conflicts are related to other packages I have on my system for which the installation of QPrism causes problems. 

As an example the QPrism install does this:

>   Attempting uninstall: pandas
>     Found existing installation: pandas 1.4.2
>     Uninstalling pandas-1.4.2:
>       Successfully uninstalled pandas-1.4.2
> 
> Successfully installed ... pandas-1.2.4

Which results in an issue with another package already installed on my system. 
> pyripherals 0.0.2 requires pandas>=1.3.1, but you have pandas 1.2.4 which is incompatible.

Similarly, the installation of QPrism downgraded _numpy_ (1.23.1 to 1.21.6) and _scipy_ packages which I heavily rely upon and prefer to have up to date. 

I'm OK with the installation of a package upgrading packages I already have installed. However, downgrading packages I already have is an undesired behavior.

**Comment by RahaviSelvarajan** [comment]
Thank you for letting us know! We have updated the Readme instructions for installing QPrism. Please create a virtual environment before installing the package.

Follow the steps given here: [https://github.com/aid4mh/QPrism/blob/main/README.md](url)
