### ISSUE TITLE
Create some automated tests 

### ISSUE THREAD

**Issue by jodemaey** [aid4mh/QPrism#2]
## Feature request ##

Please create some automated tests so that the functionality of the software can be verified. Or at least describe manual steps to test the software.

**Comment by Jana-kabrit** [comment]
Hello,
We do have testing notebooks for each module in the `test` folder.  Each notebook contains every function available in that module so you can have an overview of its functionality or test your own audio/video/TS data by rerunning the cells.
Let us know if you have any specific functions/modules that you want clarification on.
